name: dash-react-yamnet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - dash
  - dash-html-components
  - dash-bootstrap-components
  - flask
  - librosa
  - numpy
  - plotly
  - requests
  - resampy
  - pip
  - pip:
    - soundfile
    - tensorflow
    - tensorflow-hub
